# ============================================================
# Aevion autostart - run the local server at login (per user, no admin)
# Usage: powershell -NoProfile -ExecutionPolicy Bypass -File tools\autostart-server.ps1
#        powershell ... -File tools\autostart-server.ps1 -Remove
#
# Writes a HKCU\...\Run entry that starts node tools\dev-server.mjs hidden at
# YOUR login. Deliberately NOT schtasks: creating an ONLOGON task needs admin
# even when it targets the current user (Access is denied, verified on this
# machine), while a Run key is the designed, admin-free, per-user hook.
#
# The entry points at a wscript shim rather than node directly, because the
# Run key would otherwise flash a console window at every login. The server
# is idempotent: dev-server.mjs exits with EADDRINUSE if a copy is already
# listening, so a double start is harmless.
# ============================================================
param([switch] $Remove)

$ErrorActionPreference = 'Stop'

$runKey = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
$valueName = 'Aevion server'

$node = $null
foreach ($p in @(
  (Join-Path $env:USERPROFILE 'aevion-tools\node-v22.14.0-win-x64\node.exe'),
  'C:\Program Files\nodejs\node.exe',
  'C:\Program Files (x86)\nodejs\node.exe'
)) { if (Test-Path $p) { $node = $p; break } }
if (-not $node) {
  $cmd = Get-Command node -ErrorAction SilentlyContinue
  if ($cmd) { $node = $cmd.Source }
}
if (-not $node) { Write-Host 'No node.exe found.' -ForegroundColor Red; exit 1 }

$root   = Split-Path $PSScriptRoot -Parent
$server = Join-Path $root 'tools\dev-server.mjs'
if (-not (Test-Path $server)) { Write-Host "Missing $server" -ForegroundColor Red; exit 1 }

if ($Remove) {
  if (Get-ItemProperty -Path $runKey -Name $valueName -ErrorAction SilentlyContinue) {
    Remove-ItemProperty -Path $runKey -Name $valueName
    Write-Host "Removed '$valueName' from the Run key." -ForegroundColor Green
  } else {
    Write-Host "No '$valueName' entry was installed." -ForegroundColor Yellow
  }
  exit 0
}

# The shim lives in %LOCALAPPDATA%\Aevion next to the desktop launcher, so
# the login entry keeps working if the project moves (re-run this script
# after a move - it bakes in the absolute paths).
$appDir = Join-Path $env:LOCALAPPDATA 'Aevion'
New-Item -ItemType Directory -Force -Path $appDir | Out-Null
$shim = Join-Path $appDir 'aevion-server.vbs'
@"
' Generated by tools\autostart-server.ps1. Starts the Aevion local server
' with no console window; dev-server.mjs exits quietly if a copy is already
' listening, so this is safe to fire at every login.
CreateObject("WScript.Shell").Run """$node"" ""$server""", 0, False
"@ | Set-Content -Path $shim -Encoding ASCII

New-Item -Path $runKey -Force | Out-Null
Set-ItemProperty -Path $runKey -Name $valueName -Value ("wscript.exe `"$shim`"")

Write-Host ''
Write-Host 'Installed: the Aevion server starts at login.' -ForegroundColor Green
Write-Host "  run entry  HKCU\...\Run\$valueName"
Write-Host "  shim       $shim"
Write-Host "  server     $server"
Write-Host "  node       $node"
Write-Host ''
Write-Host 'Remove it any time with:  -Remove'
